---
- name: Pull and Run docker image of akshaynagpal22/spe-calculator
  hosts: all
  tasks:
    - name: Pull akshaynagpal22/spe-calculator
      docker_image:
        name: akshaynagpal22/spe-calculator
        source: pull
    - name: Create default containers
      docker_container:
        name: c1
        image: akshaynagpal22/spe-calculator
        state: present